[package]
name = "mypassman"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mypassman"
path = "main.rs"

[dependencies]
mpm-core = { path = "../core" }
mpm-crypto = { path = "../crypto" }
mpm-store = { path = "../store" }
blake3.workspace = true
clap.workspace = true
dirs.workspace = true
libc.workspace = true
rand_core.workspace = true
rpassword.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10.1"
security-framework = "3.7.0"
security-framework-sys = "2.17.0"
block2 = "0.6"
objc2 = "0.6"
objc2-foundation = "0.3.2"
objc2-local-authentication = { version = "0.3.2", features = ["block2"] }
