[package]
name = "mpm-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mpm-core = { path = "../core" }
mpm-crypto = { path = "../crypto" }
dirs.workspace = true
ed25519-dalek.workspace = true
fs2.workspace = true
thiserror.workspace = true

[dev-dependencies]
dirs.workspace = true
rand_core.workspace = true
